# Generated by Django 5.0.2 on 2024-03-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تکرار کلمه عبور'),
        ),
    ]
