# Generated by Django 5.0.2 on 2024-02-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_orderdetail_order_remove_orderdetail_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
