# Generated by Django 5.0.2 on 2024-02-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_product_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_time',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت محصول'),
        ),
    ]
