# Generated by Django 5.0.2 on 2024-02-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_factor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factor',
        ),
    ]
