# Generated by Django 5.0.2 on 2024-02-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد فروش'),
        ),
        migrations.AddField(
            model_name='product',
            name='viewset_count',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
