# Generated by Django 5.0.2 on 2024-02-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_product_order_count_product_viewset_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='viewset_count',
        ),
    ]
