# Generated by Django 5.0.2 on 2024-03-02 14:19

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان مزیت رقابتی')),
                ('description', models.TextField(verbose_name='متن مزیت رقابتی')),
            ],
            options={
                'verbose_name': 'مزیت رقابتی',
                'verbose_name_plural': 'مزیت رقابتی ها',
            },
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/', verbose_name='لوگو پایین صفحه')),
                ('title_logo', models.CharField(max_length=250, verbose_name='عنوان لوگو پایین صفحه')),
                ('Contact_title', models.CharField(max_length=250, verbose_name='عنوان یکی از فیلد های پایین صفحه')),
                ('Contact_email', models.CharField(max_length=250, verbose_name='ایمیل ما')),
                ('Contact_phone', models.CharField(max_length=11, verbose_name='شماره تلفن ما')),
                ('Contact_address', models.CharField(max_length=250, verbose_name='آدرس ما')),
                ('Access_title', models.CharField(max_length=250, verbose_name='عنوان یکی از دیگر از فیلد های پایین صفحه')),
                ('Access_description', models.CharField(max_length=250, verbose_name='متن های دسترسی سریع')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان بالا صفحه')),
                ('logo', models.ImageField(upload_to='images/', verbose_name='لوگو بالا صفحه')),
            ],
            options={
                'verbose_name': 'داینامیک هدر صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='ImageIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس صفحه')),
                ('image2', models.ImageField(upload_to='images/', verbose_name='عکس صفحه')),
            ],
            options={
                'verbose_name': 'داینامیک عکس صفحه اصلی',
                'verbose_name_plural': 'داینامیک عکس های صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='SliderIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان اسلایدر')),
                ('description', models.TextField(verbose_name='متن اسلایدر')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس اسلایدر')),
            ],
            options={
                'verbose_name': 'داینامیک اسلایدر صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='TitleIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس بالا صفحه اصلی')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان ')),
                ('title1', models.CharField(max_length=250, verbose_name='عنوان 1')),
                ('title2', models.CharField(max_length=250, verbose_name='عنوان 2')),
                ('title3', models.CharField(max_length=250, verbose_name='عنوان 3')),
                ('title4', models.CharField(max_length=250, verbose_name='عنوان 4')),
            ],
            options={
                'verbose_name': 'داینامیک عکس بالای صفحه اصلی',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='created_time',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.date(2024, 3, 2), null=True, verbose_name='تاریخ ثبت محصول'),
        ),
    ]
