# Generated by Django 5.0.2 on 2024-03-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_advantage_footer_headerindex_imageindex_sliderindex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'داینامیک پایین صفحه'},
        ),
    ]
