# Generated by Django 5.0.2 on 2024-03-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_footer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageindex',
            name='image2',
        ),
    ]
