# Generated by Django 5.0.2 on 2024-03-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_imageindex_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس مزیت رقابتی'),
        ),
    ]
