# Generated by Django 5.0.2 on 2024-03-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_advantage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='description',
        ),
    ]
