# Generated by Django 5.0.2 on 2024-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_advantage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='Access_description',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='Access_title',
        ),
        migrations.AlterField(
            model_name='footer',
            name='Contact_title',
            field=models.CharField(max_length=250, verbose_name='عنوان  فیلد  پایین صفحه'),
        ),
    ]
