# Generated by Django 5.0.2 on 2024-03-06 13:14

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_footer_access_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'داینامیک پایین صفحه', 'verbose_name_plural': 'داینامیک پایین صفحه ها'},
        ),
        migrations.AlterModelOptions(
            name='headerindex',
            options={'verbose_name': 'داینامیک هدر صفحه اصلی', 'verbose_name_plural': 'داینامیک هدر های صفحه'},
        ),
        migrations.AlterModelOptions(
            name='sliderindex',
            options={'verbose_name': 'داینامیک اسلایدر صفحه اصلی', 'verbose_name_plural': 'داینامیک اسلایدر های صفحه اصلی'},
        ),
        migrations.AlterField(
            model_name='product',
            name='created_time',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.date(2024, 3, 6), null=True, verbose_name='تاریخ ثبت محصول'),
        ),
    ]
