# Generated by Django 5.0.2 on 2024-03-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_product_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visited_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد بازدید'),
        ),
    ]
