# Generated by Django 5.0.2 on 2024-03-11 15:07

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_product_visited_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_time',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.date(2024, 3, 11), null=True, verbose_name='تاریخ ثبت محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_count',
            field=models.IntegerField(default=0, verbose_name='تعداد فروش'),
        ),
    ]
