# Generated by Django 5.0.2 on 2024-03-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_product_created_time_alter_product_order_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visited_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
