# Generated by Django 5.0.2 on 2024-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_product_visited_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=11, verbose_name='قیمت'),
        ),
    ]
