# Generated by Django 5.0.2 on 2024-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='تایید شده/ نشده'),
        ),
        migrations.AddField(
            model_name='response_comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='تایید شده/ نشده'),
        ),
    ]
