# Generated by Django 5.0.2 on 2024-03-01 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_category_options_alter_product_options_and_more'),
        ('comment', '0004_comment_is_active_response_comment_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='response_comment',
            options={'verbose_name': 'جواب کامنت', 'verbose_name_plural': 'جواب کامنت ها'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.product', verbose_name='کامنت محصول'),
        ),
    ]
