# Generated by Django 5.0.1 on 2024-04-20 12:52

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(verbose_name='نهایی شده / نشده')),
                ('payment_date', django_jalali.db.models.jDateField(auto_now=True, null=True, verbose_name='تاریخ پرداخت')),
                ('tracking_code', models.CharField(blank=True, max_length=11, null=True, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('Collecting', 'Collecting'), ('Collected', 'Collected'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Collecting', max_length=10, verbose_name='وضیعت')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید کاربران',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی تکی محصول')),
                ('count', models.IntegerField(verbose_name='تعداد')),
            ],
            options={
                'verbose_name': 'جزییات سبد خرید',
                'verbose_name_plural': 'لیست جزییات سبدهای خرید',
            },
        ),
    ]
