# Generated by Django 5.0.2 on 2024-02-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_factor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factor',
        ),
    ]
